name: 'Deploy to Deta'
description: 'Simple GitHub Action to deploy current repo to a Deta Micro'

inputs:
  deta-access-token:
    description: 'Deta access token'
    required: true
  deta-name:
    description: 'Deta micro name'
    required: true
  deta-project:
    description: 'Deta project'
    default: 'default'
    
runs:
  using: "composite"
  steps: 
    - run: echo Hello debug.
    - name: Install Deta CLI
      run: |
        curl -fsSL https://get.deta.dev/cli.sh | sh
        ls

        
