name: 'Deploy to Deta'
description: 'Simple GitHub Action to deploy current repo to a Deta Micro'

inputs:
  deta-access-token:
    description: 'Deta access token'
    required: true
  deta-name:
    description: 'Deta micro name'
    required: true
  deta-project:
    description: 'Deta project'
    default: 'default'
    
runs:
  using: "composite"
  steps: 
    - run: echo Hello debug.
      shell: bash
    - name: Install Deta CLI
      shell: bash
      run: |
        curl -fsSL https://get.deta.dev/cli.sh | sh
    - name: Clone Deta Metadata
      shell: bash
      run: |
        export DETA_ACCESS_TOKEN=${{ inputs.deta-access-token }}
        ~/.deta/bin/deta clone --name ${{ inputs.deta-name }} --project ${{ inputs.deta-project }} tmp/
        cp -r tmp/.deta .
    - name: Deploy to Deta 
      shell: bash
      run: |
        export DETA_ACCESS_TOKEN=${{ inputs.deta-access-token }}
        ~/.deta/bin/deta deploy

        
